version: '3.1'

services:
  zabbixdb:
    image: monitoringartist/zabbix-db-mariadb:latest
    volumes:
      - ./zabbixdb-storage:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
    environment:
      - MARIADB_USER=zabbix
      - MARIADB_PASS=password
    expose:
      - 3306
    networks:
      app_net:
        ipv4_address: 172.16.36.2
    restart: always

  zabbix:
    image: monitoringartist/zabbix-xxl:latest
    depends_on:
      - zabbixdb
    ports:
      - "80:80"
      - "10051:10051"
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      - ZS_DBHost=zabbixdb
      - ZS_DBUser=zabbix
      - ZS_DBPassword=password
    networks:
      app_net:
        ipv4_address: 172.16.36.3
    restart: always

volumes:
  zabbixdb-storage:
    driver: local

networks:
  app_net:
    driver: bridge
    ipam:
     driver: default
     config:
       - subnet: 172.16.36.0/24
